### ISSUE TITLE
make test fails on OSX

### ISSUE THREAD

**Issue by cipy** [johanbrandhorst/wasm-experiments#13]
```
$ make test
GOOS=js GOARCH=wasm go test -v ./test/
fork/exec /var/folders/pv/bfbhk82s1x710yyvtryq_64h0000gn/T/go-build575778572/b001/test.test: exec format error
FAIL	github.com/johanbrandhorst/wasm-experiments/test	0.002s
FAIL
make: *** [test] Error 1

$ go version
go version go1.15.3 darwin/amd64

$ tinygo version
tinygo version 0.15.0 darwin/amd64 (using go version go1.15.3 and LLVM version 10.0.1)
```

**Comment by johanbrandhorst** [comment]
Thanks for the bug report! I can reproduce this on linux too. I'll try and see what's going on.

**Comment by johanbrandhorst** [comment]
Ha, I think the issue here is that `wasmbrowsertest` isn't installed. Try running `make install-test` first. I'll update the Makefile.

**Comment by cipy** [comment]
sorry, it does the same on OSX

> $ git pull
> 
> $ make clean
> rm -f ./html/*
> 
> $ make install-test
> go install github.com/agnivade/wasmbrowsertest
> mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec
> 
> $ make test
> go install github.com/agnivade/wasmbrowsertest
> mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec
> GOOS=js GOARCH=wasm go test -v ./test/
> fork/exec /var/folders/pv/bfbhk82s1x710yyvtryq_64h0000gn/T/go-build476740187/b001/test.test: exec format error
> FAIL	github.com/johanbrandhorst/wasm-experiments/test	0.002s
> FAIL
> make: *** [test] Error 1

**Comment by johanbrandhorst** [comment]
Do you have `$GOPATH/bin` in your $PATH?
