### ISSUE TITLE
is there any examples show  how js call go package's exported function?

### ISSUE THREAD

**Issue by 2qif49lt** [johanbrandhorst/wasm-experiments#4]
Hi,is there any examples show  how js call go package's exported function?
sincere!

**Comment by johanbrandhorst** [comment]
Hi! I don't have any examples like that yet, but I could add one!

**Comment by justinclift** [comment]
@2qif49lt Does the new export example here help?

&nbsp; &nbsp; https://github.com/johanbrandhorst/wasm-experiments/tree/master/export

**Comment by 2qif49lt** [comment]
@johanbrandhorst @justinclift 

> @2qif49lt Does the new export example here help?
> 
>     https://github.com/johanbrandhorst/wasm-experiments/tree/master/export

seems to be sort of usable. =.=  
my exact  mean is  can Go build wasm from a pure Go package with public function?

like 

```
package z7z8


func Add(a int , b int) int {
	return a + b
}
```

to
```
<script>
               ...
                const go = new Go();
                let mod, inst;
                let pkg;
                WebAssembly.instantiateStreaming(fetch("hello.wasm"), go.importObject).then((result) => {
                    mod = result.module;
                    inst = result.instance;
                    
                    document.getElementById("runButton").disabled = false;
                }).catch((err) => {
                    console.error(err);
                });
                async function run() {
                   // console.clear();
                  //  inst = await WebAssembly.instantiate(mod, go.importObject); // reset instance
                    pkg = inst.exports;
                    console.log(pkg.z7z8.add(1, 2));  
                }
            </script>
        
            <button onClick="run();" id="runButton" disabled>Run</button>
```
i imagine that will be better.
Thanks a lot.

**Comment by johanbrandhorst** [comment]
No, you must include the `document.Set("whatever", js.FuncOf(...` part to assign the function to a value in the JS world.
